### ISSUE TITLE
R/W Errors when requested block > 07FF (about 16MB)

### ISSUE THREAD

**Issue by RolandJuno** [alexthecat123/ArduinoFile#3]
I'm getting read and write errors when the Lisa requests a block at location > 0x0007FF in MacWorks.

The value byteNum is a uint32_t. This line (twice in the code) sets the block number from the command buffer.

`byteNum = (commandBuffer[1] << 16 | commandBuffer[2] << 8 | commandBuffer[3]);`

This works for values between 0x00000 and 0x0007FF. It fails at 0x000800 and above giving a value of 0xFFFF800 which will cause the "Requested block is out of range" error.

I found that casting the three command buffer values to uint32_t solves the issue.

`byteNum = ((uint32_t)commandBuffer[1] << 16 | (uint32_t)commandBuffer[2] << 8 | (uint32_t)commandBuffer[3]);`

BTW I'm running the test ArduinoFile code but I suspect this affects both branches.

**Comment by alexthecat123** [comment]
Thanks for figuring this out! I've been really busy with school and haven't had much time to work on ArduinoFile stuff lately, so I really appreciate you fixing things for me. I just updated the code on both the main and 2/10 branches with your fix, so we should be good to go now!
